// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EditNoetArea: typeof import('./src/components/EditNoetArea.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NoetPreviewArea: typeof import('./src/components/NoetPreviewArea.vue')['default']
    NoteList: typeof import('./src/components/NoteList.vue')['default']
  }
}
